enable_button: 4  #Left trigger
enable_turbo_button: 5
axis_linear: 4
scale_linear: .5
scale_linear_turbo: 2
axis_angular: 0
scale_angular: 2.5
scale_angular_turbo: 3.5

# scale_linear: 0.271
# scale_linear: 0.3
# axis_angular: 0
# scale_angular: 2
# scale_angular: 1.8

joy_node:
  deadzone: 0.1
autorepeat_rate: 20
